[2022-08-07 18:01:59,904] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: student_dag.is_table_loaded manual__2022-08-07T18:01:55.169533+00:00 [queued]>
[2022-08-07 18:01:59,914] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: student_dag.is_table_loaded manual__2022-08-07T18:01:55.169533+00:00 [queued]>
[2022-08-07 18:01:59,915] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 18:01:59,915] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-07 18:01:59,915] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-07 18:01:59,931] {taskinstance.py:1377} INFO - Executing <Task(customPostgresSensor): is_table_loaded> on 2022-08-07 18:01:55.169533+00:00
[2022-08-07 18:01:59,936] {standard_task_runner.py:52} INFO - Started process 7970 to run task
[2022-08-07 18:01:59,939] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'student_dag', 'is_table_loaded', 'manual__2022-08-07T18:01:55.169533+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/students_dag.py', '--cfg-path', '/tmp/tmp2xqtp0js', '--error-file', '/tmp/tmptm861qw4']
[2022-08-07 18:01:59,940] {standard_task_runner.py:80} INFO - Job 18: Subtask is_table_loaded
[2022-08-07 18:02:00,002] {task_command.py:369} INFO - Running <TaskInstance: student_dag.is_table_loaded manual__2022-08-07T18:01:55.169533+00:00 [running]> on host 91b6e29a11f0
[2022-08-07 18:02:00,095] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ankit
AIRFLOW_CTX_DAG_ID=student_dag
AIRFLOW_CTX_TASK_ID=is_table_loaded
AIRFLOW_CTX_EXECUTION_DATE=2022-08-07T18:01:55.169533+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-07T18:01:55.169533+00:00
[2022-08-07 18:02:00,105] {base.py:68} INFO - Using connection ID 'postgres_conn' for task execution.
[2022-08-07 18:02:00,109] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 277, in execute
    poke_return = self.poke(context)
  File "/opt/airflow/plugins/Sensors/postgresCustomSensor.py", line 15, in poke
    response=cursor.execute(f"select to_regclass('{self.schemaname}.{self.tablename}')").fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
[2022-08-07 18:02:00,122] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=student_dag, task_id=is_table_loaded, execution_date=20220807T180155, start_date=20220807T180159, end_date=20220807T180200
[2022-08-07 18:02:00,133] {standard_task_runner.py:97} ERROR - Failed to execute job 18 for task is_table_loaded ('NoneType' object has no attribute 'fetchall'; 7970)
[2022-08-07 18:02:00,154] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-07 18:02:00,185] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
